version: '3'
services:
  api:
    container_name: api
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:3000'
    environment:
      HOST: ${DB_HOST}
      DIALECT: ${DIALECT}
      ENVIRONMENT: ${ENVIRONMENT}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      USERNAME: ${DB_USERNAME}
      PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DATABASE}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      CLOUD_NAME: ${CLOUD_NAME}
      DEV_DATABASE: postgres://username:pgpassword@db/code
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    restart: on-failure
  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pgpassword
